overlay: 1.0.0
x-speakeasy-jsonpath: rfc9535
info:
  title: Overlay public_v2_seo_openapi.json => public_v2_seo_openapi_overlay_editor.json
  version: 0.0.0
actions:
  - target: $["paths"]["/v2/seo/getMostValuableKeywords"]["get"]["parameters"][0]["schema"]["examples"][*]
    remove: true
  - target: $["paths"]["/v2/seo/getMostValuableKeywords"]["get"]["parameters"][0]["schema"]["examples"]
    update:
      - "domain.com"
      - "domain.com/path"
      - "host.domain.com"
      - "https://www.domain.com/full/url-including?querystrings"
  - target: $["paths"]["/v2/seo/getMostValuableKeywords"]["get"]["parameters"][0]["example"]
    update: "domain.com"
